version: '3.9'
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: aleksandr
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5433:5433"
    expose:
      - "5433"
    volumes:
      - postgres-db:/var/lib/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 5433
volumes:
  postgres-db: